### PR TITLE
Added some helper methods for offchain ownership check/mint counts

### PR DESCRIPTION
**Pull request by andrewdamelio**
### PR - Onchain Helpers

@HouseOfHufflepuff 🙏 thanks in advance for the review

#### 1) Added check_collection_ownership.cdc script
Added a OnChain method of checking if a `flowAddress` of a `CollectionGroupId` still owns the `nftIds` that were recorded for that address when the completion token was minted.

```
pub var completedCollections: {Address: [CollectionCompletedWith]}
```

Usage:

1) When the BE goes to mint a flowAccounts CollectionGroup token, we can fire an additional transaction `transactions/admin/set_completed_collection_group.cdc` and provide the `flowAddress` and the list of `nftIds` used to validate the completion. 

2) Anyone can run the following cadence script `scripts/check_collection_ownership.cdc`, and provide `collectionGroupID`, `userAddress` and get back a boolean reflecting if all the `nftIds` are still owned by the user.

    Currently `nftType` isn't stored on this struct, it's assumed whoever is calling this script would know the `nftType` that belongs to the provided `collectionGroupId`.

#### 2) Added get_collection_group_nft_count.cdc script

```
pub var collectionGroupNFTCount: {UInt64: UInt64}
```

Added a OnChain method of checking how many completed tokens for a given `collectionGroupID` have been minted.

### CODE REVIEW

**Review by HouseOfHufflepuff — APPROVED** [review]
LGTM. Nice job. Do you think you want a new event for completedWith?

**Comment by andrewdamelio** [comment]
> LGTM. Nice job. Do you think you want a new event for completedWith?

TBH i didn't even consider it, yes i do -- will update!

**Comment by andrewdamelio** [comment]
@HouseOfHufflepuff PR updated

**Review by HouseOfHufflepuff — APPROVED** [review]

**Comment by judezhu** [comment]
@andrewdamelio @HouseOfHufflepuff This is a great feature 🎉 . My idea we should fire this transaction when mint a token, since day one. We may don't have to handle the new `completeWith` event for now. but the snapshots will be kept on chain and we can replay the events later whenever we want.

**Review by judezhu — APPROVED** [review]

**Pull request merged**
